# Generated by Django 5.2.9 on 2026-05-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('heat_index', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'temperature',
            },
        ),
    ]
